### Crear un nuevo item (POST)

POST http://127.0.0.1:5000/items
Content-Type: application/json

{
  "nombre": "Proyector Epson",
  "categoria": "Electrónica",
  "cantidad": 2,
  "precio_estimado": 450.00,
  "ubicacion": "Oficina principal",
  "fecha_adquisicion": "2024-04-01",
  "owner_id": 2
}
