### Editar un curso (POST)

# Simular POST con nuevos datos del curso

PUT http://127.0.0.1:5000/items/1
Content-Type: application/json

{
  "nombre": "Proyector Epson X2",
  "categoria": "Electrónica",
  "cantidad": 3,
  "precio_estimado": 499.99,
  "ubicacion": "Sala de reuniones",
  "fecha_adquisicion": "2024-04-05",
  "owner_id": 1
}
